server:
  port: 9000
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/kotlin_blog?serverTimezone=Asia/Seoul&useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf8
    username: test
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update # 서버 켤때 데이터베이스에 새로 만들어주기 create, 기존에 있어 만들어줄 필요 없다면 update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    open-in-view: false
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        globally_quoted_identifiers: true
    show-sql: false # log4j sql쿼리 로그에 보여주기
decorator:
  datasource:
    p6spy:
      enable-logging: true # sql쿼리 로그 마킹 제거, 상용 false, 개발환경 true
